CREATE TABLE IF NOT EXISTS Game(
    GAME_NO INTEGER PRIMARY KEY AUTOINCREMENT,
    WHITE_HANDLE VARCHAR(50) NOT NULL,
    BLACK_HANDLE VARCHAR(50) NOT NULL,
    RESULT VARCHAR(256)
    )

CREATE TABLE IF NOT EXISTS Board(
    GAME_NO INTEGER,
    TURN_NO INTEGER,
    TURN TEXT CHECK(TURN IN ('White','Black')),
    BOARD TEXT NOT NULL,
    REAL_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    WHITE_TIME INTEGER,
    BLACK_TIME INTEGER,
    PRIMARY KEY (GAME_NO, TURN_NO),
    FOREIGN KEY (GAME_NO) REFERENCES Game(GAME_NO)
)